<a href="https://colab.research.google.com/github/Divyansh280/FMML-labs2023/blob/main/FMML_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Question 0: write down 3-5 methods applicable to each data type.

In [4]:
#1: int

a = 5
print(a)
print(type(a))
a += 5
b = int()
print("B type is:", type(b))

5
<class 'int'>
B type is: <class 'int'>


In [5]:
#2: dictionary

dict1 = { "1" : "A", "2" : "B", "3" : "C"}
dict1.update({"4" : "D"})
print(dict1.get("4"))
print(dict1)
print(type(dict1))
dict1.pop("3")
print(dict1)

D
{'1': 'A', '2': 'B', '3': 'C', '4': 'D'}
<class 'dict'>
{'1': 'A', '2': 'B', '4': 'D'}


In [7]:
#3: Set

set1 = set()
set1.add(1)
set1.add(2)
set1.add(3)
print(set1)
set1.add(2)
print(set1)
set1.discard(2)
print(set1)

set2 = set()
print(set1.issuperset(set2))
set1.pop()

print(set1, set2)

{1, 2, 3}
{1, 2, 3}
{1, 3}
True
{3} set()


In [14]:
#4: String

str1 = str()
str1 += "abcdefghcdcd"
str1 = str1.upper()
print(str1)
str1 = str1.capitalize()
print(str1.count("C"))
print(str1.swapcase())

ABCDEFGHCDCD
0
aBCDEFGHCDCD


In [16]:
#5: List

li = []
li.append(5)
li.pop()
li.append(10)
li.append(8)
print(type(li))
print(len(li))
print(li)
li.sort()
print(li)
li.clear()

<class 'list'>
2
[10, 8]
[8, 10]


In [19]:
#6: Tuple

Tup = ('python', 'geek', 'python', 'for', 'java', 'python')
print(Tup.index("geek"))
print(Tup.count("python"))
print(len(Tup))

1
3
6


In [20]:
#Question-1: Reverse a string
def func(a,b):
  a = a[::-1]
  b += a
  return b

a = "example1"
b = "example2"
print(func(a,b))


example21elpmaxe


In [22]:
#Question-2: List task

work_hours = [('Abby',100 , 'F'),('Billy',400, 'M'),('Cassie',800,'F'),
              ('Maggi',600,'F'),('Alex',500,'M'),('Raj',225,'M'),
               ('Penny',920,'F'),('Ben',300,'M')]
def find_highest_paid_female_worker(work_hours):
    max_hours = 0
    highest_paid_female = None

    for name, hours, gender in work_hours:
        if gender == 'F' and hours > max_hours:
            max_hours = hours
            highest_paid_female = name

    if highest_paid_female:
        pay = max_hours * 20
        print(f"The female worker is {highest_paid_female} with {max_hours} hours worked.")
        print(f"She should be paid ${pay}.")
    else:
        print("No female worker found in the list.")

find_highest_paid_female_worker(work_hours)

The female worker is Penny with 920 hours worked.
She should be paid $18400.


In [38]:
#Question-3: Matrix question

import numpy as np
arr1 = [1,1,1]
arr2 = [2,2,2]
arr3 = [3,3,3]
mat = np.vstack((arr1,arr2,arr3))
print(mat)

A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])

# Calculating the inverse of the matrix
mat1 = np.linalg.inv(A)


[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [39]:
prod = np.dot(mat,mat1)
print(prod)
print(np.size(prod))
print(np.shape(prod))

[[0.11764706 0.01633987 0.11437908]
 [0.23529412 0.03267974 0.22875817]
 [0.35294118 0.04901961 0.34313725]]
9
(3, 3)
